FROM node:alpine as builder
LABEL maintainer="admin@site15.ru"
WORKDIR /usr/src/app
COPY ./apps/rucken/package.json ./
COPY ./templates ./templates
RUN npm config set package-lock false
RUN yarn install --link-duplicates --non-interactive
RUN rm -rf ./node_modules/typescript
RUN yarn autoclean --force
COPY ./dist/apps/rucken .

# ---

FROM node:alpine
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/ /usr/src/app/
EXPOSE 5000
STOPSIGNAL SIGINT
CMD ["node", "server/main.js"]